In [11]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [12]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [13]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [14]:
movies.shape

(4803, 20)

In [15]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [16]:
movies = movies.merge(credits,on='title')

In [17]:
movies.head()
# budget
# homepage
# id
# original_language
# original_title
# popularity
# production_comapny
# production_countries
# release-date(not sure)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
import ast

In [21]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [22]:
movies.dropna(inplace=True)

In [23]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [24]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [31]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [46]:
movies['cast'] = movies['cast']
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [33]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [34]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [35]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [36]:
#movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
666,100241,"I, Frankenstein","200 years after his shocking creation, Dr. Fra...","[Horror, Thriller]","[soul, queen, anti hero, fantasy, prince, supe...","[Aaron Eckhart, Yvonne Strahovski, Bill Nighy]",[Stuart Beattie]
4678,391,A Fistful of Dollars,The Man With No Name enters the Mexican villag...,[Western],"[gang war, victim of murder, greed, hostility,...","[Clint Eastwood, Marianne Koch, Gian Maria Vol...",[Sergio Leone]
1725,3638,No Reservations,Master chef Kate Armstrong runs her life and h...,[Comedy],"[italy, competition, loss of mother, loss of s...","[Catherine Zeta-Jones, Aaron Eckhart, Abigail ...",[Scott Hicks]
3788,15059,The Loss of Sexual Innocence,The story of the sexual development of a filmm...,[Drama],[],"[Julian Sands, Saffron Burrows, Justin Chadwick]",[Mike Figgis]
2882,14778,Last Orders,Jack Dodd was a London butcher who enjoyed a p...,"[Comedy, Drama]","[based on novel, war veteran, male friendship,...","[Michael Caine, Tom Courtenay, David Hemmings]",[Fred Schepisi]

In [47]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [48]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [49]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [51]:
movies['overview'] = movies['overview']

In [52]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [53]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])
#new.head()

In [54]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [44]:
pip install -U scikit-learn scipy matplotlib

Requirement already satisfied: scikit-learn in c:\users\laharika\anaconda3\lib\site-packages (1.2.2)
Collecting scikit-learn
  Downloading scikit_learn-1.5.2-cp311-cp311-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: scipy in c:\users\laharika\anaconda3\lib\site-packages (1.11.4)
Collecting scipy
  Downloading scipy-1.14.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     -------------------------- ------------- 41.0/60.8 kB ? eta -:--:--
     -------------------------- ------------- 41.0/60.8 kB ? eta -:--:--
     -------------------------- ------------- 41.0/60.8 kB ? eta -:--:--
     -------------------------- ------------- 41.0/60.8 kB ? eta -:--:--
     -------------------------------------- 60.8/60.8 kB 230.8 kB/s eta 0:00:00
Requirement already satisfied: matplotlib in c:\users\laharika\anaconda3\lib\site-packages (3.8.0)
Collecting matplotlib
  Downloading matplotlib-3.9.2-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\laharika\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: joblib>=1.2.0 in c:\users\laharika\anaconda3\lib\site-packages (from scikit-learn) (1.2.0)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\laharika\anaconda3\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\laharika\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\laharika\anaconda3\lib\site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\laharika\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\laharika\anaconda3\lib\site-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=8 in c:\users\laharika\anaconda3\lib\site-packages (from matplotlib) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\laharika\anaconda3\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\laharika\anaconda3\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\laharika\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Downloading scikit_learn-1.5.2-cp311-cp311-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/11.0 MB 3.3 MB/s eta 0:00:04
   - -------------------------------------- 0.4/11.0 MB 5.5 MB/s eta 0:00:02
   --- ------------------------------------ 0.9/11.0 MB 7.2 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/11.0 MB 7.3 MB/s eta 0:00:02
   ----- ---------------------------------- 1.6/11.0 MB 7.4 MB/s eta 0:00:02
   ------- -------------------------------- 2.0/11.0 MB 7.3 MB/s eta 0:00:02
   ------- -------------------------------- 2.2/11.0 MB 7.3 MB/s eta 0:00:02
   ---------- ----------------------------- 2.8/11.0 MB 7.9 MB/s eta 0:00:02
   ------------ --------------------------- 3.4/11.0 MB 8.3 MB/s eta 0:00:01
   -------------- ------------------------- 3.9/11.0 MB 8.7 MB/s eta 0:00:01
   ---------------- ----------------------- 4.5/11.0 MB 8.9 MB/s eta 0:00:01
   ------------------ --------------------- 5.0/11.0 MB 9.2 MB/s eta 0:00:01
   -------------------- ------------------- 5.6/11.0 MB 9.4 MB/s eta 0:00:01
   ---------------------- ----------------- 6.1/11.0 MB 9.5 MB/s eta 0:00:01
   ----------------------- ---------------- 6.6/11.0 MB 9.6 MB/s eta 0:00:01
   -------------------------- ------------- 7.2/11.0 MB 9.8 MB/s eta 0:00:01
   --------------------------- ------------ 7.7/11.0 MB 9.8 MB/s eta 0:00:01
   ----------------------------- ---------- 8.2/11.0 MB 9.9 MB/s eta 0:00:01
   ------------------------------- -------- 8.8/11.0 MB 10.0 MB/s eta 0:00:01
   --------------------------------- ------ 9.3/11.0 MB 10.1 MB/s eta 0:00:01
   ----------------------------------- ---- 9.8/11.0 MB 10.1 MB/s eta 0:00:01
   ------------------------------------- -- 10.4/11.0 MB 10.4 MB/s eta 0:00:01
   ---------------------------------------  10.9/11.0 MB 10.6 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 10.4 MB/s eta 0:00:00
Downloading scipy-1.14.1-cp311-cp311-win_amd64.whl (44.8 MB)
   ---------------------------------------- 0.0/44.8 MB ? eta -:--:--
   ---------------------------------------- 0.3/44.8 MB 8.3 MB/s eta 0:00:06
    --------------------------------------- 0.7/44.8 MB 8.7 MB/s eta 0:00:06
   - -------------------------------------- 1.2/44.8 MB 9.6 MB/s eta 0:00:05
   - -------------------------------------- 1.7/44.8 MB 9.9 MB/s eta 0:00:05
   - -------------------------------------- 2.2/44.8 MB 10.1 MB/s eta 0:00:05
   -- ------------------------------------- 2.7/44.8 MB 10.2 MB/s eta 0:00:05
   -- ------------------------------------- 3.2/44.8 MB 10.3 MB/s eta 0:00:05
   --- ------------------------------------ 3.8/44.8 MB 10.4 MB/s eta 0:00:04
   --- ------------------------------------ 4.3/44.8 MB 10.5 MB/s eta 0:00:04
   ---- ----------------------------------- 4.8/44.8 MB 10.6 MB/s eta 0:00:04
   ---- ----------------------------------- 5.4/44.8 MB 10.7 MB/s eta 0:00:04
   ----- ---------------------------------- 5.9/44.8 MB 10.7 MB/s eta 0:00:04
   ----- ---------------------------------- 6.3/44.8 MB 10.7 MB/s eta 0:00:04
   ------ --------------------------------- 6.9/44.8 MB 10.7 MB/s eta 0:00:04
   ------ --------------------------------- 7.6/44.8 MB 10.8 MB/s eta 0:00:04
   ------- -------------------------------- 8.1/44.8 MB 10.8 MB/s eta 0:00:04
   ------- -------------------------------- 8.6/44.8 MB 10.8 MB/s eta 0:00:04
   -------- ------------------------------- 9.1/44.8 MB 10.8 MB/s eta 0:00:04
   -------- ------------------------------- 9.7/44.8 MB 10.8 MB/s eta 0:00:04
   --------- ------------------------------ 10.2/44.8 MB 10.9 MB/s eta 0:00:04
   --------- ------------------------------ 10.8/44.8 MB 11.1 MB/s eta 0:00:04
   ---------- ----------------------------- 11.3/44.8 MB 11.1 MB/s eta 0:00:04
   ---------- ----------------------------- 11.8/44.8 MB 11.1 MB/s eta 0:00:03
   ----------- ---------------------------- 12.4/44.8 MB 11.1 MB/s eta 0:00:03
   ----------- ---------------------------- 12.9/44.8 MB 11.1 MB/s eta 0:00:03
   ----------- ---------------------------- 13.2/44.8 MB 10.9 MB/s eta 0:00:03
   ------------ --------------------------- 13.5/44.8 MB 10.7 MB/s eta 0:00:03
   ------------ --------------------------- 14.0/44.8 MB 10.7 MB/s eta 0:00:03
   ------------- -------------------------- 14.6/44.8 MB 10.7 MB/s eta 0:00:03
   ------------- -------------------------- 15.1/44.8 MB 10.7 MB/s eta 0:00:03
   ------------- -------------------------- 15.6/44.8 MB 10.7 MB/s eta 0:00:03
   -------------- ------------------------- 16.2/44.8 MB 10.9 MB/s eta 0:00:03
   -------------- ------------------------- 16.7/44.8 MB 10.9 MB/s eta 0:00:03
   --------------- ------------------------ 17.3/44.8 MB 10.9 MB/s eta 0:00:03
   --------------- ------------------------ 17.8/44.8 MB 10.9 MB/s eta 0:00:03
   ---------------- ----------------------- 18.4/44.8 MB 10.9 MB/s eta 0:00:03
   ---------------- ----------------------- 18.9/44.8 MB 10.9 MB/s eta 0:00:03
   ----------------- ---------------------- 19.5/44.8 MB 10.9 MB/s eta 0:00:03
   ----------------- ---------------------- 20.0/44.8 MB 10.9 MB/s eta 0:00:03
   ------------------ --------------------- 20.5/44.8 MB 10.9 MB/s eta 0:00:03
   ------------------ --------------------- 21.0/44.8 MB 10.9 MB/s eta 0:00:03
   ------------------- -------------------- 21.6/44.8 MB 10.9 MB/s eta 0:00:03
   ------------------- -------------------- 22.1/44.8 MB 10.9 MB/s eta 0:00:03
   -------------------- ------------------- 22.7/44.8 MB 10.9 MB/s eta 0:00:03
   -------------------- ------------------- 23.3/44.8 MB 11.1 MB/s eta 0:00:02
   --------------------- ------------------ 23.7/44.8 MB 11.3 MB/s eta 0:00:02
   --------------------- ------------------ 24.3/44.8 MB 11.5 MB/s eta 0:00:02
   ---------------------- ----------------- 24.9/44.8 MB 11.5 MB/s eta 0:00:02
   ---------------------- ----------------- 25.4/44.8 MB 11.5 MB/s eta 0:00:02
   ----------------------- ---------------- 26.0/44.8 MB 11.5 MB/s eta 0:00:02
   ----------------------- ---------------- 26.5/44.8 MB 11.5 MB/s eta 0:00:02
   ------------------------ --------------- 27.0/44.8 MB 11.5 MB/s eta 0:00:02
   ------------------------ --------------- 27.5/44.8 MB 11.5 MB/s eta 0:00:02
   ------------------------- -------------- 28.1/44.8 MB 11.5 MB/s eta 0:00:02
   ------------------------- -------------- 28.6/44.8 MB 11.5 MB/s eta 0:00:02
   -------------------------- ------------- 29.1/44.8 MB 11.5 MB/s eta 0:00:02
   -------------------------- ------------- 29.7/44.8 MB 11.5 MB/s eta 0:00:02
   -------------------------- ------------- 30.2/44.8 MB 11.5 MB/s eta 0:00:02
   --------------------------- ------------ 30.7/44.8 MB 11.3 MB/s eta 0:00:02
   --------------------------- ------------ 31.2/44.8 MB 11.5 MB/s eta 0:00:02
   ---------------------------- ----------- 31.8/44.8 MB 11.5 MB/s eta 0:00:02
   ---------------------------- ----------- 32.3/44.8 MB 11.5 MB/s eta 0:00:02
   ----------------------------- ---------- 32.9/44.8 MB 11.5 MB/s eta 0:00:02
   ----------------------------- ---------- 33.4/44.8 MB 11.5 MB/s eta 0:00:01
   ------------------------------ --------- 33.9/44.8 MB 11.5 MB/s eta 0:00:01
   ------------------------------ --------- 34.5/44.8 MB 11.5 MB/s eta 0:00:01
   ------------------------------- -------- 35.0/44.8 MB 11.5 MB/s eta 0:00:01
   ------------------------------- -------- 35.6/44.8 MB 11.5 MB/s eta 0:00:01
   -------------------------------- ------- 36.0/44.8 MB 11.7 MB/s eta 0:00:01
   -------------------------------- ------- 36.6/44.8 MB 11.3 MB/s eta 0:00:01
   --------------------------------- ------ 37.1/44.8 MB 11.3 MB/s eta 0:00:01
   --------------------------------- ------ 37.6/44.8 MB 11.3 MB/s eta 0:00:01
   ---------------------------------- ----- 38.1/44.8 MB 11.3 MB/s eta 0:00:01
   ---------------------------------- ----- 38.6/44.8 MB 11.3 MB/s eta 0:00:01
   ---------------------------------- ----- 39.1/44.8 MB 11.1 MB/s eta 0:00:01
   ----------------------------------- ---- 39.5/44.8 MB 11.1 MB/s eta 0:00:01
   ----------------------------------- ---- 40.0/44.8 MB 11.1 MB/s eta 0:00:01
   ------------------------------------ --- 40.6/44.8 MB 11.1 MB/s eta 0:00:01
   ------------------------------------ --- 41.1/44.8 MB 10.9 MB/s eta 0:00:01
   ------------------------------------- -- 41.6/44.8 MB 11.1 MB/s eta 0:00:01
   ------------------------------------- -- 42.1/44.8 MB 11.1 MB/s eta 0:00:01
   -------------------------------------- - 42.7/44.8 MB 11.1 MB/s eta 0:00:01
   -------------------------------------- - 43.2/44.8 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------  43.7/44.8 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------  44.2/44.8 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------  44.8/44.8 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------  44.8/44.8 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------  44.8/44.8 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------- 44.8/44.8 MB 9.9 MB/s eta 0:00:00
Downloading matplotlib-3.9.2-cp311-cp311-win_amd64.whl (7.8 MB)
   ---------------------------------------- 0.0/7.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.8 MB 14.9 MB/s eta 0:00:01
   ----- ---------------------------------- 1.0/7.8 MB 12.9 MB/s eta 0:00:01
   ------- -------------------------------- 1.6/7.8 MB 12.4 MB/s eta 0:00:01
   ---------- ----------------------------- 2.1/7.8 MB 12.2 MB/s eta 0:00:01
   ------------- -------------------------- 2.6/7.8 MB 12.0 MB/s eta 0:00:01
   ---------------- ----------------------- 3.2/7.8 MB 11.9 MB/s eta 0:00:01
   ----------------- ---------------------- 3.5/7.8 MB 11.3 MB/s eta 0:00:01
   ------------------- -------------------- 3.8/7.8 MB 10.6 MB/s eta 0:00:01
   --------------------- ------------------ 4.2/7.8 MB 10.3 MB/s eta 0:00:01
   ----------------------- ---------------- 4.6/7.8 MB 10.1 MB/s eta 0:00:01
   -------------------------- ------------- 5.1/7.8 MB 10.3 MB/s eta 0:00:01
   ---------------------------- ----------- 5.6/7.8 MB 10.3 MB/s eta 0:00:01
   ------------------------------- -------- 6.2/7.8 MB 10.6 MB/s eta 0:00:01
   ---------------------------------- ----- 6.7/7.8 MB 10.7 MB/s eta 0:00:01
   ------------------------------------ --- 7.2/7.8 MB 10.8 MB/s eta 0:00:01
   ---------------------------------------  7.7/7.8 MB 10.8 MB/s eta 0:00:01
   ---------------------------------------  7.8/7.8 MB 10.6 MB/s eta 0:00:01
   ---------------------------------------- 7.8/7.8 MB 9.6 MB/s eta 0:00:00
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, scikit-learn, matplotlib
  Attempting uninstall: threadpoolctl
    Found existing installation: threadpoolctl 2.2.0
    Uninstalling threadpoolctl-2.2.0:
      Successfully uninstalled threadpoolctl-2.2.0
  Attempting uninstall: scipy
    Found existing installation: scipy 1.11.4
    Uninstalling scipy-1.11.4:
      Successfully uninstalled scipy-1.11.4
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.8.0
    Uninstalling matplotlib-3.8.0:
      Successfully uninstalled matplotlib-3.8.0
Successfully installed matplotlib-3.9.2 scikit-learn-1.5.2 scipy-1.14.1 threadpoolctl-3.5.0
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.

In [55]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [56]:
vector = cv.fit_transform(new['tags']).toarray()

In [57]:
vector.shape

(4806, 5000)

In [58]:
from sklearn.metrics.pairwise import cosine_similarity

In [59]:
similarity = cosine_similarity(vector)

In [60]:
similarity

array([[1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
        0.        ],
       [0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
        0.        ],
       [0.06071767, 0.06350006, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02635231, 0.02677398, ..., 1.        , 0.07352146,
        0.04774099],
       [0.0277885 , 0.        , 0.        , ..., 0.07352146, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05264981,
        1.        ]])

In [61]:
new[new['title'] == 'The Lego Movie'].index[0]

744

In [63]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [64]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman & Robin
Batman

In [65]:
import pickle

In [66]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [67]:

new.iloc[126].title

'Thor: The Dark World'

In [68]:
new['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [69]:
pickle.dump(new.to_dict(),open('movie_dict.pkl','wb'))